### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rgraebert** [xya/coroutines#1]
Hi, 

under what license is this library? I could not see any information in the source files. I wanted to check your library out for a proprietary Android app.

Thanks,

**Comment by xya** [comment]
Hi,

You're right, I didn't set any license when I first uploaded this library. I have now added a 3-clause BSD license header to all source files and headers, which should let you use it for your proprietary Android app.

Out of curiosity, what are you using coroutines for?

If you have any issue or question then please let me know!

Cheers,
Pierre-Andre

**Comment by rgraebert** [comment]
Hi Pierre-Andre,

Thanks for adding the license.

We are using Coroutines in our application to support context switches within our Lisp interpreter. It is something we implemented for all desktop platforms some time ago. As we are now working on an Android version of our app this was one missing piece.

I have asked one of the developers to check it the library and see if we can make this feature work.

Many thanks,

Roebt
